FROM nginx:latest
# ENV SERVER_NAME=example.org
COPY ./default.conf ./default.tmpl 
COPY ./checkEnv.sh ./
RUN sh ./checkEnv.sh
RUN sed "s/ENV_SERVER_NAME/${SERVER_NAME}/g" ./default.tmpl > /etc/nginx/conf.d/default.conf
